#!/usr/bin/python

import os;

print("\033[H\033[2J", end="\r");
print("Welcome to \033[32mLasto\033[0m \033[34mBoot Manager\033[0m 0.1");
print("Type 'help' for how to use manager.");
while (True):
	selecter = input("; ");
        
	if selecter == "exit":
                exit();
	elif selecter == "boot 0":
                os.system("./os");
	elif selecter == "help":
                print("  help - show all commands");
                print("  boot 0 - start lastos");
                print("  exit - exit from the boot manager");
	else:
  		print("Bad Command.");
  
