#!/usr/bin/python
import tkinter as tk;

# Creating window
root = tk.Tk();
root.title("Lasto Display");
root.minsize(640, 480);
root.geometry("640x480");
# Lasto Graphics $_$
root.configure(background="blue");
msg = tk.Label(text="Lasto Graphics $_$");
msg.configure(background="blue");
msg.pack();
root.mainloop();
