#!/usr/bin/python

import tkinter as tk;

# Creating window
root = tk.Tk();
root.title("Lasto Display");
root.minsize(640, 480);
root.geometry("640x480");
# Lasto Graphics
root.configure(background="white");
msg1 = tk.Label(text="Lasto Graphics 3410");
msg2 = tk.Label(text="GovnOS >< LastOS >< Linux");
msg1.configure(background="white");
msg2.configure(background="white");
msg1.pack();
msg2.pack();
root.mainloop();
