#!/usr/bin/python

def NewDisk(letter):
	return dict([]);

def NewFile(disk, path):
	path = path.replace("/", "\"][\"");
	exec(f"disk[\"{path}\"] = bytearray([0]);");
	return disk;

def NewDir(disk, path):
	path = path.replace("/", "\"][\"");
	exec(f"disk[\"{path}\"] = dict();");
	return disk;

disk = NewDisk("X:");
print("Loading filesystem...");
disk = NewDir(disk, "home");
disk = NewDir(disk, "bin");
disk = NewDir(disk, "usr");
disk = NewDir(disk, "home/user");
disk = NewDir(disk, "home/user/Documents");
disk = NewDir(disk, "home/user/Pictures");
disk = NewDir(disk, "home/user/Downloads");
